### PR TITLE
feat: Ability to overwrite the comment header

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by untitaker** [comment]
not sure what's going on with CI. I can run tests locally

**Comment by billyvg** [comment]
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported ... not sure we'd want to downgrade node here.... maybe try upgrading ncc?

regardless I think you need to manually `yarn dist` and check in the built files

**Comment by untitaker** [comment]
seems to work now

**Review by billyvg — APPROVED** [review]

**Comment by billyvg** [comment]
👀 not sure why I don't have access

**Pull request merged**
