### PR TITLE
fix: Generating SQL for unique_together

### PR DESCRIPTION
**Pull request by markstory**
Django cannot generate the SQL for a unique_together removal when the migrations have already been applied. If we rollback to the previous version first then SQL generation will work as the constraints being removed exist again.

I've not been able to verify these changes in GitHub Actions, but I was able to reproduce the error I've been having with my dashboard widget migration locally, and was able to run `sqlmigrate` after rolling back the new migration.

### CODE REVIEW

**Comment by billyvg** [comment]
@markstory When I get some time, I can test out this solution. I think it's preferable to handle this in the action since this is used in sentry + getsentry.

**Comment by armenzg** [comment]
> Django cannot generate the SQL for a unique_together removal when the migrations have already been applied. If we rollback to the previous version first then SQL generation will work as the constraints being removed exist again.
> 
> I've not been able to verify these changes in GitHub Actions, but I was able to reproduce the error I've been having with my dashboard widget migration locally, and was able to run `sqlmigrate` after rolling back the new migration.

Do you have a test case for this? or an example?

**Comment by markstory** [comment]
> Do you have a test case for this? or an example?

I think I ran into this when changing indexes for the unique_together indexes around dashboards. I'm not 100% sure how it happened anymore though. Given it hasn't come up again, we can probably close this out and revisit if/when it happens again.

**Comment by armenzg** [comment]
> Django cannot generate the SQL for a unique_together removal when the migrations have already been applied. If we rollback to the previous version first then SQL generation will work as the constraints being removed exist again.
> 
> I've not been able to verify these changes in GitHub Actions, but I was able to reproduce the error I've been having with my dashboard widget migration locally, and was able to run `sqlmigrate` after rolling back the new migration.

Do you have a test case for this? or an example?

> > Do you have a test case for this? or an example?
> 
> I think I ran into this when changing indexes for the unique_together indexes around dashboards. I'm not 100% sure how it happened anymore though. Given it hasn't come up again, we can probably close this out and revisit if/when it happens again.

Sounds good. We will look into it quickly.

**Comment by armenzg** [comment]
I tinkered a bit with this.

I created a migration that [drops a unique_together](https://github.com/getsentry/sentry/pull/25625/files#diff-025a08d4250c559637c64de2455592d7dd5952ca978eee14432bfd47c02a8272L34):
```diff
     class Meta:
         app_label = "sentry"
         db_table = "sentry_incidentproject"
-        unique_together = (("project", "incident"),)
```
and this is [the SQL](https://github.com/getsentry/sentry/pull/25625#issuecomment-827077615) that was generated:
image

I also run the command manually, applied, failed, unapplied, and succeeded:
```
❯ sentry django sqlmigrate sentry 0187_random_name --> Worked
❯ sentry upgrade --noinput
❯ sentry django sqlmigrate sentry 0187_random_name --> Failed
❯ sentry django migrate sentry 0186_add_externalactor
❯ sentry django sqlmigrate sentry 0187_random_name --> Worked
```

From what I understand, this does not seem to me a very important bug to fix and we would be fine not fixing it. Would you be fine with that?

Full output
```
❯ sentry django sqlmigrate sentry 0187_random_name
20:12:52 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
20:12:53 [INFO] sentry.plugins.github: apps-not-configured
BEGIN;
--
-- Alter unique_together for incidentproject (0 constraint(s))
--
ALTER TABLE "sentry_incidentproject" DROP CONSTRAINT "sentry_incidentproject_project_id_incident_id_366ae072_uniq";
COMMIT;

❯ sentry upgrade --noinput
20:29:37 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
20:29:39 [INFO] sentry.plugins.github: apps-not-configured
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, jira_ac, nodestore, sentry, sessions, sites, social_auth
Running migrations:
  Applying sentry.0183_make_codemapping_unique_on_projectcodeowners... OK
  Applying sentry.0184_copy_useroptions_to_notificationsettings_2... OK
  Applying sentry.0185_rm_copied_useroptions... OK
  Applying sentry.0186_add_externalactor... OK
  Applying sentry.0187_random_name... OK
Creating missing DSNs
Correcting Group.num_comments counter

sentry on  armenzg/generate-sql-for-unique-together [$] via  v12.19.0 via 🐍 v3.6.13 took 5s
❯ sentry django sqlmigrate sentry 0187_random_name
20:32:08 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
20:32:10 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
  File "/Users/armenzg/.pyenv/versions/3.6.13/bin/sentry", line 33, in <module>
    sys.exit(load_entry_point('sentry', 'console_scripts', 'sentry')())
  File "/Users/armenzg/code/sentry/src/sentry/runner/__init__.py", line 195, in main
    func(**kwargs)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/armenzg/code/sentry/src/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/armenzg/code/sentry/src/sentry/runner/commands/django.py", line 14, in django
    execute_from_command_line(argv=[ctx.command_path] + list(management_args))
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/core/management/commands/sqlmigrate.py", line 33, in execute
    return super(Command, self).execute(*args, **options)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/core/management/commands/sqlmigrate.py", line 62, in handle
    sql_statements = executor.collect_sql(plan)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/db/migrations/executor.py", line 223, in collect_sql
    state = migration.apply(state, schema_editor, collect_sql=True)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/db/migrations/operations/models.py", line 536, in database_forwards
    getattr(new_model._meta, self.option_name, set()),
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 365, in alter_unique_together
    self._delete_composed_index(model, fields, {'unique': True}, self.sql_delete_unique)
  File "/Users/armenzg/.pyenv/versions/3.6.13/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 394, in _delete_composed_index
    ", ".join(columns),
ValueError: Found wrong number (0) of constraints for sentry_incidentproject(project_id, incident_id)

sentry on  armenzg/generate-sql-for-unique-together [$] via  v12.19.0 via 🐍 v3.6.13
❯ sentry django migrate sentry 0186_add_externalactor
20:36:50 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
20:36:51 [INFO] sentry.plugins.github: apps-not-configured
Operations to perform:
  Target specific migration: 0186_add_externalactor, from sentry
Running migrations:
  Rendering model states... DONE
  Unapplying sentry.0187_random_name... OK

❯ sentry django sqlmigrate sentry 0187_random_name
20:37:20 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
20:37:22 [INFO] sentry.plugins.github: apps-not-configured
BEGIN;
--
-- Alter unique_together for incidentproject (0 constraint(s))
--
ALTER TABLE "sentry_incidentproject" DROP CONSTRAINT "sentry_incidentproject_project_id_incident_id_366ae072_uniq";
COMMIT;
```

**Comment by markstory** [comment]
> From what I understand, this does not seem to me a very important bug to fix and we would be fine not fixing it. Would you be fine with that?

That works for me.

**Pull request closed without merging**
